serverless-offline:
    port: 4000
stage: ${opt:stage, self:provider.stage}
stg_cmo: ${opt:stage, 'desa'}
stg_cmo_upper: ${self:custom.env.${self:custom.stg_cmo}}
nom_project: ANLUTESTV3 # cambiar tambien serveless service linea 1-
nom_api_rest: ${self:custom.region-name.${self:custom.stg_cmo}}NET${self:custom.stg_cmo_upper}APIREST${self:custom.nom_project}
nom_lambda: ${self:custom.region-name.${self:custom.stg_cmo}}COM${self:custom.stg_cmo_upper}LMB${self:custom.nom_project}
nom_dynamodb: ${self:custom.region-name.${self:custom.stg_cmo}}COM${self:custom.stg_cmo_upper}TBL${self:custom.nom_project}
nom_sqs: ${self:custom.region-name.${self:custom.stg_cmo}}COM${self:custom.stg_cmo_upper}SQS${self:custom.nom_project}
env:
    desa: DESA
environments:
    desa: DESARROLLO
region: 
    desa: us-east-1 
region-name: 
    desa: UE2
security-group-id:
    desa: sg-6862af17
bucketDeploy: 
    desa: bucketservelss030622  
bucketS3:
    desa: bucketservelss030622
role:
    desa: "arn:aws:iam::154838795707:role/despliegue_aws_ext"